-- 뷰 추가 ( 정규동 )

-- BRANCHLIST 뷰
CREATE OR REPLACE VIEW BRANCHLIST
AS
SELECT ROWNUM RNUM, BRANCH_NUM, BRANCH_MANAGER_EMAIL, BRANCH_ADDRESS,
BRANCH_PHONE, BRANCH_IMG, BRANCH_WEBSITE, BRANCH_POINT,
BRANCH_OPTION_SHOWER, BRANCH_OPTION_PARK, BRANCH_OPTION_UNIFORM, 
BRANCH_OPTION_SHOES, BRANCH_OPTION_BALL, BRANCH_OPTION_INOUT,
BRANCH_DELETE_STATUS, BRANCHINFO, BRANCH_DETAILINFO, 
BRANCH_NOTES, STADIUM_NUM, STADIUM_BRANCH_NUM, 
STADIUM_NAME, STADIUM_MATCH_MEMBER, STADIUM_RESERVATION_START_TIME,
STADIUM_RESERVATION_END_TIME, STADIUM_DELETE_STATUS
FROM(SELECT * FROM BRANCH JOIN STADIUM ON(BRANCH_NUM = STADIUM_BRANCH_NUM)
WHERE BRANCH_DELETE_STATUS = 'N' ORDER BY BRANCH_NUM DESC);

-- TEAMMEMBERLIST
CREATE OR REPLACE VIEW TEAMMEMBERLIST
AS
SELECT SUPPORTER_EMAIL, SUPPORT_TEAM, TEAMMEMBER_NUM, POSITION, APPLICATION_STATUS, DELETE_STATUS, TEAM_CODE, TEAM_LEADER, TEAM_NUM, TEAM_NAME, TEAM_GENDER,
TEAM_AGE, TEAM_REGION, TEAM_POINT, TEAM_MARK_IMG, TEAM_ACTIVE_LASTDAY, TEAM_DELETE_STATUS
FROM(SELECT * FROM TEAMMEMBER JOIN TEAM ON(SUPPORT_TEAM = TEAM_CODE)
WHERE DELETE_STATUS = 'N');

COMMIT;
