CREATE TABLE BOARD_ATTACHMENT(
FILE_ID NUMBER PRIMARY KEY,
BOARD_NUM NUMBER NOT NULL,
ORIGIN_NAME VARCHAR2(255) NOT NULL,
CHANGE_NAME VARCHAR2(255) NOT NULL,
FILE_PATH VARCHAR2(1000) NOT NULL,
UPLOAD_DATE DATE DEFAULT SYSDATE,
FILE_DELETED_STATUS VARCHAR2(1) DEFAULT 'N',
FOREIGN KEY (BOARD_NUM) REFERENCES BOARD
);

CREATE SEQUENCE SEQ_FID;
