CREATE TABLE STADIUM(
    stadium_num NUMBER PRIMARY KEY,
    stadium_branch_num VARCHAR2(10) NOT NULL,
    stadium_name VARCHAR2(10) NOT NULL,
    stadium_match_member VARCHAR2(10),
    stadium_reservation_start_time NUMBER NOT NULL,
    stadium_reservation_end_time NUMBER NOT NULL,
    stadium_delete_status VARCHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT CK_STADIUM_DELETE_STATUS CHECK(stadium_delete_status IN ('Y', 'N')),
    CONSTRAINT FK_STADIUM_BRANCH_NUM FOREIGN KEY(stadium_branch_num) REFERENCES BRANCH(branch_num) ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_STADIUM_NUM
START WITH 1
INCREMENT BY 1
MAXVALUE 1000
NOCYCLE
NOCACHE;

CREATE OR REPLACE VIEW STADIUMLIST
AS
SELECT ROWNUM RNUM, DESCSTADIUM.*
FROM (SELECT *
        FROM STADIUM
            JOIN BRANCH ON (stadium_branch_num = BRANCH_NUM)
        WHERE STADIUM_DELETE_STATUS = 'N'
        ORDER BY STADIUM_NUM DESC) DESCSTADIUM;
